language: python

python:
    - "2.7"

notifications:
    email: false

install:
    - pip install -r requirements.txt

before_script:
    - sed 's/http/https/g' config.py.dist > config.py

script:
    - flake8 app
    - flake8 tests
    - flake8 config.py
    - nosetests
